language: php
php:
  - 5.3
  - 5.4
env:
  global:
    - secure: "BQaBZsxUbNQeI4N8y46ge1FSQ3BB5LcuM04ThkHIzdXKR5NGpkZGEu9PpWBh6YO8rPNmucP/Gx1Y6Ou31RLWJgbhyEQLGQgud4+xcZoa9o0xwhUeaPeA88IrvZp9VzYLK6Hf4Scnz0xc1sMZmiaTmrrKJ0R0vS+HMIyKMXO7kb8="
    - secure: "JKrCdmnOB0TPwOORfQOaljbGWR2rGIWhM+sWk07CsG8+KRBtC1I/roXLT5MZQXGg28n+vQLrT/csNg1aGP1rCezTJ8xoUH3sQ24F6JNjbSSx7QWDDBaSDXL+BWdtJeaaKiIFjTrFfKOWVOYEE3ZDUgV6Wu1mACDQbd84FOgHoHQ="
    - WP_MULTISITE=0
  matrix:
    - WP_VERSION=latest
    - WP_VERSION=3.8
    - WP_VERSION=3.7.1
# - WP_VERSION=3.6.1  WP_MULTISITE=0
# - WP_VERSION=3.5.2  WP_MULTISITE=0
# - WP_VERSION=3.4.2  WP_MULTISITE=0
# - WP_VERSION=3.3.3  WP_MULTISITE=0
before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
