language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1
    - WP_VERSION=3.7.1 WP_MULTISITE=0
    - WP_VERSION=3.7.1 WP_MULTISITE=1
    - WP_VERSION=3.6.1 WP_MULTISITE=0
    - WP_VERSION=3.6.1 WP_MULTISITE=1
    - WP_VERSION=3.5.2 WP_MULTISITE=0
    - WP_VERSION=3.5.2 WP_MULTISITE=1
    - WP_VERSION=3.4.2 WP_MULTISITE=0
    - WP_VERSION=3.4.2 WP_MULTISITE=1
    - WP_VERSION=3.3.3 WP_MULTISITE=0
    - WP_VERSION=3.3.3 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: WP_VERSION=${WP_VERSION} WP_MULTISITE=${WP_MULTISITE} phpunit
