language: php
php:
- 5.3
env:
  global:
  - secure: "FIKNH5o9Ao9sRulTlsafELWS1i2zuk40tU/PaGcsP0WtBB3B8dUYG2f4hhvnwCwcTBVOvFYYfm+euSWw2qj3vCbELv2jlg54Oruxg4OmyTq+vF/WLU113S7lkQrkYWqNDcA+pqzNvqq4mVzGVh1yaEV7JBDFkrnTyrBuufwgU3Y="
  - WL_DISABLE_SPARQL_UPDATE_QUERIES_BUFFERING=true
  - WL_SSL_VERIFY_ENABLED=true
  - WL_SSL_V1_FORCED=true
  matrix:
  - WP_VERSION=3.9.1  WP_MULTISITE=0

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
notifications:
  slack: insideout10:NcslbQWVmD4YPInDq8TpBIno
sudo: false