language: php
php:
  - 5.3
  - 5.4
env:
  global:
    - secure: "KgQPZIIRH3WlhMUnSkvjIqBzHrJCD5wu0XSV2v+3Qgi9IsY33CqEgW1C9VNTW67sNXBkApQXDPsuJM0uOnylgWRaoHDQPO6/vYrzOSU66zVsugxzQgfT7io06iR9wPuVLx2sl0arBrJ/DL3FoFFl64hWvgOpmhethcFcNJRn7Ng="
    - secure: "JKrCdmnOB0TPwOORfQOaljbGWR2rGIWhM+sWk07CsG8+KRBtC1I/roXLT5MZQXGg28n+vQLrT/csNg1aGP1rCezTJ8xoUH3sQ24F6JNjbSSx7QWDDBaSDXL+BWdtJeaaKiIFjTrFfKOWVOYEE3ZDUgV6Wu1mACDQbd84FOgHoHQ="
    - secure: "LS5Zi1fKKf/xzN0Q71ArvxOfexqiFRAZWQ6lM8dQ+C01shSqbI50SxyoX78p6JUe6pIfqxCy1csjagy5y7UNwVE3Pp6Z1tiv+nLmyVnF29Fj8lq0YxaXGG0egcgwEARe7uqc3fRN1YpW2nG75WQSRdTUJkPdbXsUe4aWjM+bjDE="
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=3.8    WP_MULTISITE=0
    - WP_VERSION=3.7.1  WP_MULTISITE=0
    # - WP_VERSION=3.6.1  WP_MULTISITE=0
    # - WP_VERSION=3.5.2  WP_MULTISITE=0
    # - WP_VERSION=3.4.2  WP_MULTISITE=0
    # - WP_VERSION=3.3.3  WP_MULTISITE=0
before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
