# We need `sudo` because we're going to install Apache with PHP.
# See https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required

# Set the language to PHP since we're going to setup a WordPress web site.
language: php

php:
  - "5.6"

# Cache the node_modules folder.
# See https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  directories:
    - node_modules

addons:
  # Have Travis CI start a SauceLabs Connect instance for us.
  sauce_connect: true

env:
  global:
    # SauceLabs environment vars.
    - secure: "BPMK2gsJp6pL9rQ+qJUJaCiILGI5DTn91bcEeOOguiPtg2EUMpZWG3fvyIoFJzGu8Mi7jluP60au00cmYK8QbtwJyDACqsmDRwV+1JFrl1ipZJ2R/KVksFfzsb8qOnNG9ejCSkobHj3IrR5l+bCJU2PPa9/d/lc3DFhZaNW4T3k="
    - secure: "MWJrwnQ09c+ekylfFMuky4W3V5rokJBGMXTZp5/PsDgY2eL684/77vIjUQ6tBNVrKIMhh5VbAoJ3FIY3PkbCVoz0JN3hRJ4JZNtqn1X/ABC7i0csC09ObLZO55/F2kHawPofvysdg/h9xfvd7vUQsoqd4FQcyxEzbUGmv2XenTE="

services:
  # Require MySQL.
  - mysql

before_script:
  # Create WordPress' database.
  - mysql -e 'create database wordpress default charset utf8mb4 default collate utf8mb4_general_ci;'
  # Install Apache.
  - .ci/travis/install_apache.sh
  # Install wp-cli.
  - .ci/travis/install_wp_cli.sh
  # Install WordPress.
  - .ci/travis/install_wordpress.sh
  # Install an update version of NodeJS. Note that this cannot be put in a sh file as nvm must retain its choice.
  - . $HOME/.nvm/nvm.sh
  - nvm install 6 --reinstall-packages-from=node
  - nvm use 6
  - node --version
  # Install Node dependencies.
  - npm install

# Finally launch the script.
script: npm run test:e2e