language: php
php:
- 5.3
env:
  global:
  - secure: "NB4P/P1/Gzje1/mOseVZqkIdaxI5vEgnlUUEmNRBtAT0CMt3c3pLSfzRtKrFfuJzoXpahxf8pC1R+Ljjf+QCC+2ECqjGCPSSv1tIj0L/H+c9UtbpPQIwD6kv7dPBYedZ6eNAgGjK1DXhrAuSnNaYJrZ35N6tv06B0KmniY6pJnk="
  - WL_DISABLE_SPARQL_UPDATE_QUERIES_BUFFERING=true
  - WL_SSL_VERIFY_ENABLED=true
  - WL_SSL_V1_FORCED=true
  matrix:
  - WP_VERSION=3.9.1  WP_MULTISITE=0

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
notifications:
  slack: insideout10:NcslbQWVmD4YPInDq8TpBIno
sudo: false